### PR TITLE
Add GitHub Workflows

### PR DESCRIPTION
**Pull request by rorymchugh**
## Description

Add GitHub Workflows to perform a release with [semantic release](https://github.com/semantic-release/semantic-release), lint git commits with [commitlint](https://github.com/conventional-changelog/commitlint) , and run Terraform format 

## What Changed?

- Add `.github/workflows/release.yml`
- Add  `.github/workflows/commitlint.yml`
- Add `.github/workflows/terraform-fmt.yml`
- Add `.github/actions/terraform-fmt/action.yml`
- Add `.releaserc.json`
- Add `.commitlintrc.mjs`
- Add `.github/pull_request_template.md`

## Reason For Change

Adding GitHub Worklflows provides a framework to ensure good commit hygiene and Terraform code formatting, along with automating the release process

## Checklist For Reviewer

- [x] You understand the reason for the change and how it fits into the existing codebase
- [x] For changes that relate to a deployment, you understand how the change will affect any dependent Live environments
- [x] You understand the scope of the change and the commit messages reflect this, e.g. where you consider the change to be a breaking change, at least one commit message should include the body "BREAKING CHANGE: ..."
- [x] You have requested changes to the Pull Request if required, or raised comments suggesting improvements
- [x] All Review comments and requests for changes have been resolved, or assigned Issues
- [x] All GitHub Actions jobs pass

### CODE REVIEW

**Comment by jlf44** [comment]
I just wanted to check the behaviour here, does it automatically format the Terraform code, or does it fail if it is misformatted?

I have no issue with automatic formatting, but I think that we don't necessarily need to reject a commit if the code and/or comments have an inconsistent style, so long as it's functional.  We want to minimise any hurdles to people new to Terraform in contributing, as this will need to be adopted by team members unfamiliar with AWS / Terraform / Containers and they will already be being asked to pick up a lot.

**Comment by rorymchugh** [comment]
> I just wanted to check the behaviour here, does it automatically format the Terraform code, or does it fail if it is misformatted?
> 
> I have no issue with automatic formatting, but I think that we don't necessarily need to reject a commit if the code and/or comments have an inconsistent style, so long as it's functional. We want to minimise any hurdles to people new to Terraform in contributing, as this will need to be adopted by team members unfamiliar with AWS / Terraform / Containers and they will already be being asked to pick up a lot.

This doesn't automatically format, but it will fail if running `terraform fmt -check` produces any difference to the codebase supplied. My view is that this is not placing a big hurdle to newcomers to Terraform, as running `terraform fmt -recursive` from the command line will automatically format all Terraform code in the directory and subdirectories. Having this check is a way to ensure the code adheres to best practices for Terraform code in terms of readability and layout. It is also a minimal way to ensure the code is valid, as `fmt` will pick up issues like missing closing brackets, invalid function names, etc etc.

**Comment by jlf44** [comment]
> This doesn't automatically format, but it will fail if running `terraform fmt -check` produces any difference to the codebase supplied. My view is that this is not placing a big hurdle to newcomers to Terraform, as running `terraform fmt -recursive` from the command line will automatically format all Terraform code in the directory and subdirectories. Having this check is a way to ensure the code adheres to best practices for Terraform code in terms of readability and layout. It is also a minimal way to ensure the code is valid, as `fmt` will pick up issues like missing closing brackets, invalid function names, etc etc.

Can we automate the formatting? In practice we have had issues with the linting like this causing a persistent hurdle to making lots of small changes in other projects.  Perhaps with sufficient documentation in the README on what's required before a commit we can trial this.

**Comment by jlf44** [comment]
Perhaps we can consider making a commit script that includes linting commands.

**Review by jlf44 — APPROVED** [review]
This looks good, thanks for adding the README.

**Pull request merged**
